Suggestion to adding conversion functions from and to 64 bit float value
ARM-software/CMSIS-DSP pull request #40
Opened 2022-08-18 12:35 UTC by Silfurion

Hello,

With the rise of ARMv8 processors, the use of the float64 bit version of CMSIS-DSP functions will become more and more frequent. Following this logic it will also be more common to make conversions to or from float64 type. Moreover in our projects we have to be able to convert from int to float64 and vice versa.

It is in this context that we would like to suggest new functions for conversion to or from float64 bit type inspired by float32 bit versions. 

We thank you in advance and wish you a good day

2022-08-31 05:53 UTC, christophe0606 requested changes
Minor issues with float constants which should be double constants.
I'll need to write tests for those new functions. Writing tests takes time ... so this PR won't be merged quickly. I'll do my best.

2022-08-31 05:53 UTC, christophe0606 commented on Source/SupportFunctions/arm_f64_to_q15.c
> +    in = (*pIn++ * 32768.0f);
Don't use float constant in a float64 code.

2022-08-31 05:53 UTC, christophe0606 commented on Source/SupportFunctions/arm_f64_to_q7.c
> + * Copyright (C) 2010-2021 ARM Limited or its affiliates. All rights reserved.
Should be 2022. 
I have not looked at other files to check if there is a similar issue.

2022-09-15 08:17 UTC, jbr-smtg commented
Bonjour @christophe0606, most issues should be fixed now. Let me know if you need further fixes.

2022-11-03 10:58 UTC, christophe0606 commented
I've finally added the tests, cleaned and  merged.

2022-11-03 10:58 UTC, closed without merging